import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'
import { ToggleProvider } from '@/Context/ToggleContect'
import DataProvider from '@/Context/DataContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToggleProvider>
          <DataProvider>
            <div className='container'>
              <Navbar />
              {children}
              <Footer />
            </div>
          </DataProvider>
        </ToggleProvider>

      </body>
    </html>
  )
}
